  - name: Get Debian codename
    ansible.builtin.command: lsb_release -cs
    register: lsb_release_result

  - name: Set fact for Debian codename
    ansible.builtin.set_fact:
      debian_codename: "{{ lsb_release_result.stdout }}"

  - name: Ensure apt-transport-https is installed
    ansible.builtin.apt:
      name: apt-transport-https
      state: present
  
  - name: Check if the key file exists for hashicorp
    ansible.builtin.stat:
      path: "{{ hashicorp.key_path }}"
    register: key_exists
  
  - name: Download GPG key for hashicorp
    ansible.builtin.get_url:
      url: "{{ hashicorp.key_url }}"
      dest: "/tmp/hashicorp-archive-keyring.gpg"
    when: hashicorp.key_url is defined and not key_exists.stat.exists

  - name: Add GPG key for hashicorp
    ansible.builtin.command: >
      gpg --dearmor -o {{ hashicorp.key_path }} /tmp/hashicorp-archive-keyring.gpg
    when: hashicorp.key_url is defined and not key_exists.stat.exists

  - name: Add repository for vagrant
    ansible.builtin.apt_repository:
      repo: "{{ hashicorp.repo }}"
      filename: "vagrant"
      state: present
  
  - name: Install vagrant and libvirt dependencies
    ansible.builtin.apt:
      pkg: "{{ libvirt_dependencies_vagrant }}"
      state: present

  - name: Install the vagrant-libvirt plugin
    become_user: "{{ local_user }}"
    ansible.builtin.command:
      cmd: vagrant plugin install vagrant-libvirt
    args:
      creates: /home/{{ local_user }}/.vagrant.d/gems/*/gems/vagrant-libvirt-*/

  - name: Ensure the current user is added to the libvirt group
    ansible.builtin.user:
      name: "{{ local_user }}"
      groups: libvirt
      append: yes

  - name: Enable and start the libvirtd service
    ansible.builtin.service:
      name: libvirtd
      enabled: yes
      state: started
