---
- name: Verify if the host is Debian
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == "Debian"
    msg: "This role is only supported on Debian systems."

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Set fact username on the host
  ansible.builtin.set_fact:
    local_user: "{{ username_on_the_host.stdout }}"

- name: Template contrib.list
  ansible.builtin.template:
    src: contrib.list.j2
    dest: /etc/apt/sources.list.d/contrib.list
    mode: '0644'

- name: Update and upgrade package list
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  tags:
    - update

- name: Install a list of packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"

- name: Update file hosts
  ansible.builtin.include_tasks:
    file: update_hosts.yml

- name: install package from deb
  ansible.builtin.include_tasks:
    file: install_from_deb.yml

- name: Install software
  ansible.builtin.include_tasks:
    file: install_software.yml
  loop: "{{ software_list }}"
  loop_control:
    loop_var: software

- name: Install vagrant with libvirt
  ansible.builtin.include_tasks:
    file: install_vagrant_with_libvirt.yml

- name: Install starship
  ansible.builtin.include_tasks:
    file: install_startship.yml

- name: Modify file .bashrc
  ansible.builtin.include_tasks:
     file: uncomment_alias_bashrc.yml
  loop: "{{ alias_list_to_uncomment }}"
  loop_control:
    loop_var: alias    