---
# - name: Ensure asdf is loaded in the current shell
#   ansible.builtin.shell: "source /home/{{ local_user }}/.asdf/asdf.sh"
#   register: asdf_shell_loaded
#   changed_when: false
#   tags:
#     - asdf
#     - load

- name: Add plugin if not already added
  ansible.builtin.command: "asdf plugin-add {{ item.name }} {{ item.url }}"
  loop: "{{ asdf_plugins }}"
  register: plugin_addition
  changed_when: plugin_addition.rc == 0
  failed_when: plugin_addition.rc != 0 and 'already' not in plugin_addition.stderr
  tags:
    - asdf
    - plugin
  become_user: "{{ local_user }}"

- name: Install the specified version for each plugin
  ansible.builtin.command: "asdf install {{ item.name }} {{ item.version }}"
  loop: "{{ asdf_plugins }}"
  tags:
    - asdf
    - install
  become_user: "{{ local_user }}"

- name: Set the specified version as global
  ansible.builtin.command: "asdf global {{ item.name }} {{ item.version }}"
  loop: "{{ asdf_plugins }}"
  tags:
    - asdf
    - global
  become_user: "{{ local_user }}"
