---
- name: Add asdf to bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ local_user }}/.bashrc"
    line: |
      . /home/{{ local_user }}/.asdf/asdf.sh
      . /home/{{ local_user }}/.asdf/completions/asdf.bash
    create: true
    state: present
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0644'
  tags:
    - asdf
    - configure


- name: Display message to reload bashrc
  ansible.builtin.debug:
    msg: "Please run 'source ~/.bashrc' or restart your terminal to apply asdf changes."
  tags:
    - asdf
    - notify
