---
# Variables for the vagrant_libvirt role
hashicorp_software_gpg:
  key_path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  key_url: https://apt.releases.hashicorp.com/gpg
  repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

hashicorp_software_software:
  - vagrant
  - terraform

hashicorp_software_dependencies:
  - libvirt-dev
  # - libvirt-bin
  - qemu-kvm
  # - libvirt-daemon
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - nfs-common
  - nfs-kernel-server
  - build-essential
  - zlib1g-dev
  - ruby-dev
  - libxml2-dev
  - libxslt-dev
  - libguestfs-tools
